# ──────────────────────────────────────────────────────────
#              STARSHIP CONFIGURATION - NIGHT LIGHT
# ──────────────────────────────────────────────────────────

# ========== GENERAL SETTINGS ==========
add_newline = false
format = """
$directory\
$git_branch\
$git_status\
$git_state\
$python\
$line_break\
$character
"""

palette = "night_light"

# ========== DIRECTORY MODULE ==========
[directory]
style = "bold lavender"
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = '…/'
format = "[ $path ]($style)"
disabled = false

[directory.substitutions]
"Developer" = "󰲋 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

# ========== GIT MODULE ==========
[git_branch]
symbol = " "
style = "bold mauve"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bold red"
staged = '[ +$count](green)'
untracked = '[?$count](yellow)'
conflicted = '[!$count](red)'
deleted = '[-$count](red)'
modified = '[~$count](mauve)'
renamed = '[»$count](lavender)'
format = '([$all_status]($style) )'

[git_state]
style = "bold mauve"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

# ========== PROMPT CHARACTER ==========
[character]
success_symbol = '[❯](bold lavender)'
error_symbol = '[❯](bold red)'
vicmd_symbol = '[❮](bold yellow)'
disabled = false

# ========== LANGUAGE/TOOL SYMBOLS ==========
[c]
symbol = " "
style = "green"

[cpp]
symbol = " "
style = "green"

[cmake]
symbol = " "
style = "green"

[python]
symbol = " "
style = "green"
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

# ========== OPERATING SYSTEMS SYMBOLS ==========
[os.symbols]
Arch = " "
Debian = " "
Linux = " "
Macos = " "
Raspbian = " "
Ubuntu = " "
Windows = "󰍲 "

# ========== COLOR PALETTE ==========
[palettes.night_light]
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
lavender = "#b4befe"
lavender_bg = "#b4befe"
text_bg = "#cdd6f4"
mauve = "#cba6f7"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
peach = "#fab387"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
blue = "#89b4fa"
sapphire = "#74c7ec"
sky = "#89dceb"
teal = "#94e2d5"
flamingo = "#f2cdcd"
maroon = "#eba0ac"
pink = "#f5c2e7"
rosewater = "#f5e0dc"