# ──────────────────────────────────────────────────────────
#              STARSHIP CONFIGURATION
# ──────────────────────────────────────────────────────────

# ========== GENERAL SETTINGS ==========
add_newline = false
# """$os$username$hostname$directory$os$git_branch$line_break$character"""
format = """
$directory \
$git_branch\
$git_status\
$python\
$line_break\
$character
"""

palette = "catppuccin_mocha"

# ========== DIRECTORY MODULE ==========
[directory]
format = "[$path](bold peach)"
read_only = " 󰌾"
truncation_length = 3           # Shorten path to 3 segments
truncation_symbol = '…/'

[directory.substitutions]
"Developer" = "󰲋 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

# ========== GIT MODULE ==========
[git_branch]
symbol = " "
style = "sapphire"
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = "sapphire"
format = '([$all_status$ahead_behind]($style) )'

# ========== LANGUAGE/TOOL SYMBOLS ==========
[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[docker_context]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "
style = "yellow"
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

# ========== OPERATING SYSTEMS SYMBOLS ==========
[os.symbols]
Arch = " "
Debian = " "
Linux = " "
Macos = " "
Raspbian = " "
Ubuntu = " "
Windows = "󰍲 "

# ========== COLOR PALETTE ==========
[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"